spring:
  application:
    name: PK4U
  data:
    mongodb:
      uri: mongodb+srv://mariamunoz495:J4IvOQoTYE0mjKlM@cluster0.j63hf9r.mongodb.net/pk4u?retryWrites=true&w=majority&appName=Cluster0
server:
  port: 8080